In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# input data (hours of sleep, hours of study)
X = np.array([[3,5], [5,1], [10,2]])

# normalized X
X_norm = X / np.max(X)
print("X_norm =")
print(X_norm)

# output data (test score)
y = np.array([[75], [83], [93]])

# normalized y
y_norm = y/100
print("y_norm =")
print(y_norm)

# Neural Network properties
inputLayerSize = 2
outputLayerSize = 1
hiddenLayerSize = 3

# Define synapse weights
W1 = np.random.randn(inputLayerSize, hiddenLayerSize)
W2 = np.random.randn(hiddenLayerSize, outputLayerSize)

# Apply the first weights to inputs to get hidden layer activity
Z2 = np.dot(X_norm, W1)
print("Z2 =")
print(Z2)

# Define our activation function
def sigmoid(z):
    #Apply sigmoid activation function to scalar, vector, or matrix
    return 1/(1+np.exp(-z))

# Apply the activation function to our activity levels
a2 = sigmoid(Z2)
print("a2 =")
print(a2)

# Apply the second weights to the hidden layer
Z3 = np.dot(a2, W2)
print("Z3 =")
print(Z3)

# Apply the activation function to produce prediction for yHat
yHat = sigmoid(Z3)

# Compare yhat to known y_norm
print("--------------")
print("How did we do?")
print("y_norm:")
print(y_norm)
print("yHat:")
print(yHat)

X_norm =
[[0.3 0.5]
 [0.5 0.1]
 [1.  0.2]]
y_norm =
[[0.75]
 [0.83]
 [0.93]]
Z2 =
[[-0.43853158 -0.25462671 -0.48718568]
 [ 0.06290777 -0.57049393 -0.67505722]
 [ 0.12581554 -1.14098786 -1.35011443]]
a2 =
[[0.39209092 0.43668504 0.38055677]
 [0.51572176 0.36112286 0.33736537]
 [0.53141246 0.24213904 0.20585166]]
Z3 =
[[-0.49333407]
 [-0.54026648]
 [-0.41350034]]
--------------
How did we do?
y_norm:
[[0.75]
 [0.83]
 [0.93]]
yHat:
[[0.37910846]
 [0.36812559]
 [0.3980731 ]]


&#169; Copyright 2018,  Michigan State University Board of Trustees